### ISSUE TITLE
Change the gap between arrows, maybe also have borders.

### ISSUE THREAD

**Issue by abbjetmus** [Midhun-MP/progress_stepper#3]
Thank you for the previous change!

I wonder if also the gap between arrows can be changed, currently they are to big?

Also if a border can be added to the arrows? 

![image](https://github.com/Midhun-MP/progress_stepper/assets/65755086/0072d47d-388b-488b-8daa-68065aa6c4f6)

**Comment by Midhun-MP** [comment]
Already working on the space adjustment.
